### ISSUE TITLE
Does not work with Redmine 1.4.2

### ISSUE THREAD

**Issue by myanimal** [thegcat/redmine_ical#2]
I haven't been able to get this plugin to work with 1.4.1 or 1.4.2. Not sure exactly what the problem is. Will this plugin be updated to work with newer versions of Redmine?

I cloned the git repo, then ran the patch:

```
[~/rails_apps/redmine]# patch -p 1 < vendor/plugins/redmine_ical/extra/redmine_ical.patch
patching file app/controllers/application_controller.rb
Reversed (or previously applied) patch detected!  Assume -R? [n] y
Hunk #1 succeeded at 88 (offset 17 lines).
patching file app/views/calendars/show.html.erb
Hunk #1 succeeded at 30 with fuzz 2 (offset 2 lines).
```

Then, when performing the following rake, I get an error:

```
[~/rails_apps/redmine]# rake db:migrate_plugins RAILS_ENV=production
rake aborted!
undefined method `accept_key_auth' for CalendarsController:Class
```

And if I try to load a page, the following error appears in my mongrel log:

```
rails_apps/redmine-1.4/vendor/plugins/redmine_ical/lib/redmine_ical/patch_redmine_classes.rb:82:in `included': undefined method `accept_key_auth' for CalendarsController:Class (NoMethodError)
```

**Comment by thegcat** [comment]
The problem is internal changes to the auth methods in Redmine.

I could probably update it to work with a current Redmine version, but I don't use Redmine anymore, so there will be sometime when I won't update it any longer. I'm also willing to give control of the plugin to a new maintainer.

**Comment by myanimal** [comment]
I would appreciate it if you did update it to work with Redmine 1.4 stable.

I will try find time to go through the code in more detail and see if it is something I would consider maintaining (lack of time being the usual problem)

Thanks for the response.

**Comment by thegcat** [comment]
837bccc4ec6f5634ab54d2a200a126b6b4cb8cf8 (current newest version) should work with Redmine 1.3.0 and newer.

**Comment by myanimal** [comment]
Thanks, I can confirm this plugin now works with Redmine 1.4.2.

Next time I have a problem I will try fix it myself first and provide a pull request if I succeed.
